version: "3.5"

services:
    elastic:
        image: radiator/elastic-plwiki:latest
        ports:
            - "9300:9300"
            - "9200:9200"
        networks: 
            - main
  
    frontend:
        image: radiator/wiki-search-engine-frontend:latest
        ports: 
            - "3000:3000"

    backend:
        image: clue/json-server
        ports: 
            - "4000:80"
        volumes:
            - ./categories.json:/data/db.json
          
          
networks:
    main:
        name: custom_network
              